fos_user:
    db_driver: orm
    firewall_name: api
    user_class: AppBundle\Entity\User
    from_email:
        address:        noreply@beercoders.com
        sender_name:    Tactic
    resetting:
        email:
            from_email:
                address:        resetting@beercoders.com
                sender_name:    Beer Coders Resetting
            template: Email/password_resetting.email.twig
