#CONTROLLER
services:
  crud_controller.users:
    class: "%vardius_crud.controller.class%"
    factory: ["@vardius_crud.controller.factory", get]
    arguments: ['AppBundle:User', /users, '@form.type.users', null, null, '@base.actions_provider']
    tags:
        - { name: vardius_crud.controller }

  crud_controller.files:
    class: "%vardius_crud.controller.class%"
    factory: ["@vardius_crud.controller.factory", get]
    arguments: ['AppBundle:File', /files, '@form.type.files', null, null, '@base.actions_provider']
    tags:
        - { name: vardius_crud.controller }
