#FORMS
services:
  form.type.users:
      class: AppBundle\Form\Type\UserType
      tags:
          - { name: form.type, alias: user }

  form.type.files:
      class: AppBundle\Form\Type\FileType
      tags:
          - { name: form.type, alias: file }

  form.type.tags:
      class: AppBundle\Form\Type\TagType
      tags:
          - { name: form.type, alias: tag }

