#LIST VIEWS
services:
  users.list_view:
    class: AppBundle\ListView\UserListViewProvider
    parent: vardius_list.list_view.provider

  files.list_view:
    class: AppBundle\ListView\FileListViewProvider
    parent: vardius_list.list_view.provider

  tags.list_view:
    class: AppBundle\ListView\TagListViewProvider
    parent: vardius_list.list_view.provider